// svelte/src/Settings.svelte
<script>
	export let origami = {};
  export let tool;
  export let active;
  export let strain;
  export let foldAmount;
  export let showTouches;
  export let showShadows;
  export let backgroundColor;
	export let frontColor;
	export let backColor;
	export let lineColor;
	export let lineOpacity;
  export let error;
  export let reset;
  export let integration;
  export let axialStiffness;
  export let faceStiffness;
  export let joinStiffness;
	export let creaseStiffness;
	export let dampingRatio;
	// throws error if file is not a valid JSON format
	// event handler for file dialog <input>
	let files;
	$: if (files) {
		const reader = new FileReader();
		reader.onload = event => {
			try {
				origami = JSON.parse(event.target.result);
			} catch (error) {
				window.alert(error);
			}
		};
		if (files.length) {
			reader.readAsText(files[0]);
		}
	}
</script>

<div class={"container"}>
	<input type="file" bind:files>

	<h3>
		simulator active
		<input type="checkbox" bind:checked={active} />

	</h3>

	<h3>fold amount</h3>
	<input
		type="range"
		min="0"
		max="1"
		step="0.01"
		disabled={!active}
		bind:value={foldAmount} />

	<h3>pointer tool</h3>
	<input
		type="radio"
		id="radio-webgl-tool-trackball"
		name="radio-webgl-tool"
		bind:group={tool}
		value="trackball" />
	<label for="radio-webgl-tool-trackball">trackball</label>
	<input
		type="radio"
		id="radio-webgl-tool-pull"
		name="radio-webgl-tool"
		bind:group={tool}
		value="pull" />
	<label for="radio-webgl-tool-pull">pull</label>

	<h3>
		show strain
		<input type="checkbox" disabled={!active} bind:checked={strain} />
	</h3>

	<h3>
		show touches
		<input type="checkbox" bind:checked={showTouches} />
	</h3>

	<h3>
		show shadows
		<input type="checkbox" disabled={strain} bind:checked={showShadows} />
	</h3>

	<h3>
		front
		<input type="text" class="medium" bind:value={frontColor} />
	</h3>
	<h3>
		back
		<input type="text" class="medium" bind:value={backColor} />
	</h3>
	<h3>
		lines
		<input type="text" class="medium" bind:value={lineColor} />
	</h3>
	<input
		type="range"
		min="0"
		max="1"
		step="0.02"
		bind:value={lineOpacity} />
	<h3>
		background
		<input type="text" class="medium" bind:value={backgroundColor} />
	</h3>

	<h3>integration</h3>
	<input
		type="radio"
		name="radio-integration"
		id="radio-integration-euler"
		value="euler"
		bind:group={integration} />
	<label for="radio-integration-euler">euler</label>
	<input
		type="radio"
		name="radio-integration"
		id="radio-integration-verlet"
		value="verlet"
		bind:group={integration} />
	<label for="radio-integration-verlet">verlet</label>

	<h3>
		axial stiffness
		<input type="text" class="short" bind:value={axialStiffness} />
	</h3>
	<input
		type="range"
		min="10"
		max="100"
		step="1"
		bind:value={axialStiffness} />

	<h3>
		face stiffness
		<input type="text" class="short" bind:value={faceStiffness} />
	</h3>
	<input
		type="range"
		min="0"
		max="5"
		step="0.02"
		bind:value={faceStiffness} />

	<h3>
		join stiffness
		<input type="text" class="short" bind:value={joinStiffness} />

	</h3>
	<input
		type="range"
		min="0"
		max="3"
		step="0.01"
		bind:value={joinStiffness} />

	<h3>
		crease stiffness
		<input type="text" class="short" bind:value={creaseStiffness} />

	</h3>
	<input
		type="range"
		min="0"
		max="3"
		step="0.01"
		bind:value={creaseStiffness} />

	<h3>
		damping ratio
		<input type="text" class="short" bind:value={dampingRatio} />

	</h3>
	<input
		type="range"
		min="0.01"
		max="0.5"
		step="0.01"
		bind:value={dampingRatio} />

	<h3>
		error
		<input type="text" class="long" disabled={!active} bind:value={error} />
	</h3>

	<button
		disabled={!active}
		on:click={reset}>reset model</button>
	<br />

</div>

<style>
	.container {
		background-color: #0009;
		z-index: 2;
		position: absolute;
		top: 0;
		left: 0;
		padding: 0.5rem;
		overflow-y: auto;
		max-height: 100vh;
	}
	.container > * {
		margin: 0.33rem 0;
	}
	/*.container input[type=radio] + * {*/
	.container input {
		margin: 0rem 0.25rem;
	}
	.long { width: 8rem; }
	.medium { width: 5.5rem; }
	.short { width: 2.5rem; }
</style>

// reactjs/src/Settings.jsx
import "./Settings.css";

const Settings = (props) => {
	// throws error if file is not a valid JSON format
	// event handler for file dialog <input>
	const fileDialogOnInput = (e) => {
		const reader = new FileReader();
		reader.onload = event => {
			try {
				props.setOrigami(JSON.parse(event.target.result));
			} catch (error) {
				window.alert(error);
			}
		};
		if (e.target.files.length) {
			reader.readAsText(e.target.files[0]);
		}
	};

	return (
		<div className="Container">
			<input type="file" onInput={fileDialogOnInput} />

			<h3>
				simulator active
				<input
					type="checkbox"
					checked={props.active}
					onClick={() => props.setActive(!props.active)}
				/>
			</h3>

			<h3>fold amount</h3>
			<input
				type="range"
				min="0"
				max="1"
				step="0.01"
				disabled={!props.active}
				value={props.foldAmount}
				onInput={e => props.setFoldAmount(e.target.value)} />

			<h3>pointer tool</h3>
			<input
				type="radio"
				name="radio-webgl-tool"
				value="radio-webgl-tool-trackball"
				onClick={() => props.setTool("trackball")}
				checked={props.tool === "trackball"} />
			<label for="radio-webgl-tool-trackball">trackball</label>
			<input
				type="radio"
				name="radio-webgl-tool"
				value="radio-webgl-tool-pull"
				onClick={() => props.setTool("pull")}
				checked={props.tool === "pull"} />
			<label for="radio-webgl-tool-pull">pull</label>

			<h3>
				show strain
				<input
					type="checkbox"
					disabled={!props.active}
					checked={props.strain}
					onClick={() => props.setStrain(!props.strain)}
				/>
			</h3>

			<h3>
				show touches
				<input
					type="checkbox"
					checked={props.showTouches}
					onClick={() => props.setShowTouches(!props.showTouches)}
				/>
			</h3>

			<h3>
				show shadows
				<input
					type="checkbox"
					disabled={props.strain}
					checked={props.showShadows}
					onClick={() => props.setShowShadows(!props.showShadows)}
				/>
			</h3>

			<h3>integration</h3>
			<input
				type="radio"
				name="radio-integration"
				value="radio-integration-euler"
				onClick={() => props.setIntegration("euler")}
				checked={props.integration === "euler"} />
			<label for="radio-integration-euler">euler</label>
			<input
				type="radio"
				name="radio-integration"
				value="radio-integration-verlet"
				onClick={() => props.setIntegration("verlet")}
				checked={props.integration === "verlet"} />
			<label for="radio-integration-verlet">verlet</label>

			<h3>
				axial stiffness
				<input
					type="text"
					className="Short"
					value={props.axialStiffness}
				/>
			</h3>
			<input
				type="range"
				min="10"
				max="100"
				step="1"
				value={props.axialStiffness}
				onInput={e => props.setAxialStiffness(e.target.value)} />

			<h3>
				face stiffness
				<input
					type="text"
					className="Short"
					value={props.faceStiffness}
				/>
			</h3>
			<input
				type="range"
				min="0"
				max="5"
				step="0.02"
				value={props.faceStiffness}
				onInput={e => props.setFaceStiffness(e.target.value)} />

			<h3>
				join stiffness
				<input
					type="text"
					className="Short"
					value={props.joinStiffness}
				/>
			</h3>
			<input
				type="range"
				min="0"
				max="3"
				step="0.01"
				value={props.joinStiffness}
				onInput={e => props.setJoinStiffness(e.target.value)} />

			<h3>
				crease stiffness
				<input
					type="text"
					className="Short"
					value={props.creaseStiffness}
				/>
			</h3>
			<input
				type="range"
				min="0"
				max="3"
				step="0.01"
				value={props.creaseStiffness}
				onInput={e => props.setCreaseStiffness(e.target.value)} />

			<h3>
				damping ratio
				<input
					type="text"
					className="Short"
					value={props.dampingRatio}
				/>
			</h3>
			<input
				type="range"
				min="0.01"
				max="0.5"
				step="0.01"
				value={props.dampingRatio}
				onInput={e => props.setDampingRatio(e.target.value)} />

			<h3>
				error
				<input
					type="text"
					className="Long"
					disabled={!props.active}
					value={props.error}
				/>
			</h3>

			<button
				disabled={!props.active}
				onClick={() => props.reset()}>reset model</button>
			<br />

		</div>
	);
};

export default Settings;
