// svelte/src/WebGL/TrackballView.svelte
<!--
	TrackballView for Svelte (c) Kraft
	MIT license
-->

<!-- 
	@component
	Extends the ThreeView component to include a three.js
	TrackballControls; otherwise, the functionality is the same as ThreeView.
	
	@props
	see ThreeView for its props, additionally, this
	component offers these optional props (none are required), all relate
	to the setup of the trackball controlls:
	- enabled (boolean)
	- maxDistance (number)
	- minDistance (number)
	- panSpeed (number)
	- rotateSpeed (number)
	- zoomSpeed (number)
	- dynamicDampingFactor (number)
-->
<script>
	import { onDestroy } from "svelte";
	import { TrackballControls } from "three/examples/jsm/controls/TrackballControls";
	import ThreeView from "./ThreeView.svelte";
	// ThreeView component
	export let didMount = () => {};
	export let didResize = () => {};
	export let animate = () => {};
	// this component
	export let enabled = true;
	export let maxDistance = 100;
	export let minDistance = 0.1;
	export let panSpeed = 1;
	export let rotateSpeed = 4;
	export let zoomSpeed = 16;
	export let dynamicDampingFactor;
	let trackball;

	$: if (trackball) { trackball.enabled = enabled; }
	$: if (trackball) { trackball.maxDistance = maxDistance; }
	$: if (trackball) { trackball.minDistance = minDistance; }
	$: if (trackball) { trackball.panSpeed = panSpeed; }
	$: if (trackball) { trackball.rotateSpeed = rotateSpeed; }
	$: if (trackball) { trackball.zoomSpeed = zoomSpeed; }
	$: if (trackball) { trackball.dynamicDampingFactor = dynamicDampingFactor; }

	const didMountHandler = ({ renderer, scene, camera }) => {
		trackball = new TrackballControls(camera, renderer.domElement.parentNode);
		// bubble up event handler
		if (didMount) {
			didMount({ renderer, scene, camera });
		}
	};

	const didResizeHandler = (event) => {
		trackball.handleResize();
		// bubble up event handler
		if (didResize) {
			didResize(event);
		}
	};

	const animateHandler = () => {
		trackball.update();
		// bubble up event handler
		if (animate) {
			animate();
		}
	};

	onDestroy(() => trackball.dispose());
</script>

<ThreeView
	didMount={didMountHandler}
	didResize={didResizeHandler}
	animate={animateHandler}
/>

// reactjs/src/WebGL/TrackballView.jsx
/**
 * TrackballView for React (c) Kraft
 * MIT license
 */
import { useEffect } from "react";
import { TrackballControls } from "three/examples/jsm/controls/TrackballControls";
import ThreeView from "./ThreeView.jsx";
/**
 * @description Extends the ThreeView component to include a three.js
 * TrackballControls; otherwise, the functionality is the same as ThreeView.
 * @param {object} props see ThreeView for its props, additionally, this
 * component offers these optional props (none are required), all relate
 * to the setup of the trackball controlls:
 * - enabled (boolean)
 * - maxDistance (number)
 * - minDistance (number)
 * - panSpeed (number)
 * - rotateSpeed (number)
 * - zoomSpeed (number)
 * - dynamicDampingFactor (number)
 */
const TrackballView = (props) => {
	let trackball;

	const didMount = ({ renderer, scene, camera }) => {
		trackball = new TrackballControls(camera, renderer.domElement.parentNode);
		// bubble up event handler
		if (props.didMount) {
			props.didMount({ renderer, scene, camera });
		}
	};

	// trackball dealloc ?
	useEffect(() => {
		return () => { if (trackball) { trackball.dispose(); }};
	})

	useEffect(() => {
		if (trackball) { trackball.enabled = props.enabled; }
	}, [props.enabled, trackball]);

	useEffect(() => {
		if (trackball) { trackball.maxDistance = props.maxDistance; }
	}, [props.maxDistance, trackball]);

	useEffect(() => {
		if (trackball) { trackball.minDistance = props.minDistance; }
	}, [props.minDistance, trackball]);

	useEffect(() => {
		if (trackball) { trackball.panSpeed = props.panSpeed; }
	}, [props.panSpeed, trackball]);

	useEffect(() => {
		if (trackball) { trackball.rotateSpeed = props.rotateSpeed; }
	}, [props.rotateSpeed, trackball]);

	useEffect(() => {
		if (trackball) { trackball.zoomSpeed = props.zoomSpeed; }
	}, [props.zoomSpeed, trackball]);

	useEffect(() => {
		if (trackball) { trackball.dynamicDampingFactor = props.dynamicDampingFactor; }
	}, [props.dynamicDampingFactor, trackball]);

	const didResize = (event) => {
		if (trackball) { trackball.handleResize(); }
		// bubble up event handler
		if (props.didResize) {
			props.didResize(event);
		}
	};

	const animate = () => {
		if (trackball) { trackball.update(); }
		// bubble up event handler
		if (props.animate) {
			props.animate();
		}
	};

	return (
		<ThreeView
			didMount={didMount}
			didResize={didResize}
			animate={animate}
		/>
	);
};

export default TrackballView;
